version: '3.8'

services:
  api:
    container_name: api
    image: paulettanachtrieb/api:latest
    ports:
      - '3000:3000'
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
