name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker build image as latest version
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api:latest .

      - name: Docker push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api:latest
